version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - static_volume:/home/upload-api/api/staticfiles
      - upload_volume:/home/upload-api/api/uploads
    depends_on:
      - api
  api:
    build: .
    command: gunicorn upload_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/upload-api/api/staticfiles
      - upload_volume:/home/upload-api/api/uploads
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:7-alpine

  celery:
    restart: always
    build: .
    command: celery -A  api  worker  -l info
    volumes:
      - upload_volume:/home/upload-api/api/uploads
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - api
volumes:
  data:
  static_volume:
  upload_volume: