# Generated by Django 4.1.7 on 2023-02-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=300)),
                ("status", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source"],
            },
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.AlterField(
            model_name="userrecord",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userrecord",
            name="email",
            field=models.CharField(max_length=150),
        ),
    ]
