# Generated by Django 4.1.7 on 2023-02-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_fileobject_delete_file_alter_userrecord_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrecord",
            name="national_id",
            field=models.CharField(max_length=50),
        ),
    ]
