# Generated by Django 4.1.7 on 2023-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_userrecord_national_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileobject",
            name="offset",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userrecord",
            name="email",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="userrecord",
            name="national_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
